from __future__ import annotations

import json
from dataclasses import replace
from importlib.resources import files
from pathlib import Path

import pytest
from cryptography.hazmat.primitives.asymmetric import ed25519, rsa
from cryptography.hazmat.primitives.serialization import Encoding, PublicFormat
from jsonschema import Draft202012Validator
from package_b_support import PLAN_REQUEST_JOB_ID, PLAN_REQUEST_WORKFLOW_REF

from ci_coordinator.execution_orchestration import (
    digest_adapter_file,
    parse_target_execution_registry,
)
from ci_coordinator.repo_context import parse_dependency_graph_artifact
from ci_coordinator.runner_capacity import parse_test_manifest
from ci_coordinator.target_artifacts import (
    TargetArtifactsAdmissionError,
    TargetArtifactsRenderError,
    check_artifacts,
    check_plan_trust_root,
    parse_target_artifacts_source,
    render_plan_trust_root,
    render_target_artifacts,
    write_artifacts,
)
from ci_coordinator.target_artifacts.cli import main

ROOT = Path(__file__).resolve().parents[4]
FIXTURE_DIRECTORY = ROOT / "fixtures" / "target-repository" / ".ci-coordinator"
NATIVE_FIXTURE_DIRECTORY = ROOT / "fixtures" / "native-target-repository" / ".ci-coordinator"
SOURCE_PATH = FIXTURE_DIRECTORY / "target-artifacts-source.v1.json"
SCHEMA_DIRECTORY = ROOT / "docs" / "specs" / "ci-coordinator-runtime"
CONTROL_FILENAME = "ci-coordinator.cjs"


def test_fixture_source_renders_runtime_admitted_schema_valid_artifacts() -> None:
    source = parse_target_artifacts_source(SOURCE_PATH.read_bytes())
    rendered = render_target_artifacts(source)
    registry = parse_target_execution_registry(rendered.execution_registry)

    assert registry is not None
    workflow = registry.workflows[0]
    assert workflow.plan_request_job_id == PLAN_REQUEST_JOB_ID
    assert workflow.plan_request_workflow_ref == PLAN_REQUEST_WORKFLOW_REF
    assert rendered.control_bundle.startswith(
        b"// Generated by scripts.target_control_bundle; do not edit; source-sha256="
    )
    assert parse_test_manifest(rendered.test_manifest) is not None
    assert (
        parse_dependency_graph_artifact(
            rendered.dependency_graph,
            retrieved_for_sha="a" * 40,
            trusted=True,
        )
        is not None
    )
    for schema_name, value in (
        ("target-artifacts-source.schema.v1.json", json.loads(SOURCE_PATH.read_bytes())),
        (
            "target-execution-registry.schema.v1.json",
            json.loads(rendered.execution_registry),
        ),
        ("test-manifest.schema.v1.json", json.loads(rendered.test_manifest)),
        ("dependency-graph.schema.v1.json", json.loads(rendered.dependency_graph)),
        (
            "plan-trust-root.schema.v1.json",
            json.loads((FIXTURE_DIRECTORY / "plan-trust-root.v1.json").read_bytes()),
        ),
    ):
        schema = json.loads((SCHEMA_DIRECTORY / schema_name).read_bytes())
        Draft202012Validator.check_schema(schema)
        Draft202012Validator(schema).validate(value)


def test_packaged_schemas_are_byte_exact_normative_mirrors() -> None:
    resources = files("ci_coordinator.target_artifacts.resources")
    for schema_name in (
        "target-artifacts-source.schema.v1.json",
        "target-execution-registry.schema.v1.json",
        "test-manifest.schema.v1.json",
        "dependency-graph.schema.v1.json",
        "plan-trust-root.schema.v1.json",
    ):
        assert (
            resources.joinpath(schema_name).read_bytes()
            == (SCHEMA_DIRECTORY / schema_name).read_bytes()
        )


@pytest.mark.parametrize(("count", "admitted"), [(16, True), (17, False)])
def test_service_profile_bound_matches_source_and_registry_admission(
    count: int,
    admitted: bool,
) -> None:
    service_profile_ids = [f"service-{index:02d}" for index in range(count)]
    source = json.loads(SOURCE_PATH.read_bytes())
    _object(_array(source["executionProfiles"])[0])["serviceProfileIds"] = service_profile_ids
    registry = json.loads((FIXTURE_DIRECTORY / "execution-registry.v1.json").read_bytes())
    _object(_array(registry["profiles"])[0])["serviceProfileIds"] = service_profile_ids

    if admitted:
        parsed_source = parse_target_artifacts_source(json.dumps(source).encode())
        assert (
            parse_target_execution_registry(
                render_target_artifacts(parsed_source).execution_registry
            )
            is not None
        )
        assert parse_target_execution_registry(json.dumps(registry).encode()) is not None
    else:
        with pytest.raises(TargetArtifactsAdmissionError):
            parse_target_artifacts_source(json.dumps(source).encode())
        assert parse_target_execution_registry(json.dumps(registry).encode()) is None


def test_packaged_control_bundle_is_a_byte_exact_target_mirror() -> None:
    resources = files("ci_coordinator.target_artifacts.resources")
    packaged = resources.joinpath(CONTROL_FILENAME).read_bytes()
    for fixture_directory in (FIXTURE_DIRECTORY, NATIVE_FIXTURE_DIRECTORY):
        assert packaged == (fixture_directory / CONTROL_FILENAME).read_bytes()


@pytest.mark.parametrize(
    "fixture_directory",
    (FIXTURE_DIRECTORY, NATIVE_FIXTURE_DIRECTORY),
    ids=("witness-shards", "native-job-set"),
)
def test_fixture_workflow_digests_bind_the_actual_workflow_bytes(
    fixture_directory: Path,
) -> None:
    source = json.loads((fixture_directory / "target-artifacts-source.v1.json").read_bytes())
    registry = json.loads((fixture_directory / "execution-registry.v1.json").read_bytes())
    source_bindings = {
        str(_object(item)["path"]): str(_object(item)["sha256"])
        for item in _array(source["adapterWorkflowFiles"])
    }
    registry_bindings = {
        str(_object(item)["path"]): str(_object(item)["sha256"])
        for item in _array(registry["adapterFiles"])
        if str(_object(item)["path"]) in source_bindings
    }
    repository_root = fixture_directory.parent

    assert registry_bindings == source_bindings
    assert {
        path: digest_adapter_file((repository_root / path).read_bytes()) for path in source_bindings
    } == source_bindings


def test_native_fixture_is_an_exact_reproducible_native_job_set() -> None:
    source_path = NATIVE_FIXTURE_DIRECTORY / "target-artifacts-source.v1.json"
    source = parse_target_artifacts_source(source_path.read_bytes())
    rendered = render_target_artifacts(source)
    registry = parse_target_execution_registry(rendered.execution_registry)

    assert registry is not None
    assert tuple(workflow.execution_kind for workflow in registry.workflows) == ("native-job-set",)
    assert parse_test_manifest(rendered.test_manifest) is not None
    assert len(rendered.by_filename()) == 4
    assert {filename: content for filename, content in rendered.by_filename()} == {
        path.name: path.read_bytes()
        for path in NATIVE_FIXTURE_DIRECTORY.iterdir()
        if path.name != "target-artifacts-source.v1.json"
    }


def test_render_is_order_invariant_and_rejects_duplicate_or_dangling_identities() -> None:
    source_mapping = json.loads(SOURCE_PATH.read_bytes())
    baseline = render_target_artifacts(
        parse_target_artifacts_source(json.dumps(source_mapping).encode())
    )
    source_mapping["dependencyGraph"]["nodes"].reverse()
    source_mapping["dependencyGraph"]["nodes"][0]["riskClasses"].reverse()

    reordered = render_target_artifacts(
        parse_target_artifacts_source(json.dumps(source_mapping).encode())
    )

    assert reordered == baseline
    source_mapping["dependencyGraph"]["nodes"][0]["dependents"] = ["missing/path"]
    with pytest.raises(TargetArtifactsAdmissionError):
        parse_target_artifacts_source(json.dumps(source_mapping).encode())


def test_native_target_source_admits_an_empty_shard_manifest() -> None:
    source_mapping = json.loads(SOURCE_PATH.read_bytes())
    source_mapping["tests"] = []
    for workflow in source_mapping["executionWorkflows"]:
        workflow["executionKind"] = "native-job-set"
        workflow["fallbackJobId"] = None
    for profile in source_mapping["executionProfiles"]:
        profile["executionKind"] = "native-job-set"

    rendered = render_target_artifacts(
        parse_target_artifacts_source(json.dumps(source_mapping).encode())
    )

    manifest = parse_test_manifest(rendered.test_manifest)
    assert manifest is not None
    assert manifest.tests == ()
    assert manifest.duration_history == ()


def test_write_and_check_modes_detect_exact_byte_drift(tmp_path: Path) -> None:
    source = tmp_path / "source.json"
    source.write_bytes(SOURCE_PATH.read_bytes())
    source.chmod(0o640)
    authored = tmp_path / "authored.txt"
    authored.write_bytes(b"Authored input must survive artifact generation.\n")
    output = tmp_path / "generated"

    def snapshot() -> dict[str, tuple[int, int, bytes]]:
        return {
            path.relative_to(tmp_path).as_posix(): (
                path.lstat().st_mode,
                path.lstat().st_mtime_ns,
                path.read_bytes(),
            )
            for path in tmp_path.rglob("*")
            if path.is_file() or path.is_symlink()
        }

    authored_before = snapshot()
    rendered = render_target_artifacts(parse_target_artifacts_source(source.read_bytes()))
    expected_outputs = (
        "execution-registry.v1.json",
        "test-manifest.v1.json",
        "dependency-graph.v1.json",
        "ci-coordinator.cjs",
    )
    assert check_artifacts(output, rendered) == expected_outputs
    assert snapshot() == authored_before

    write_artifacts(output, rendered)
    after_write = snapshot()
    assert set(after_write) == set(authored_before) | {
        f"generated/{name}" for name in expected_outputs
    }
    assert {path: after_write[path] for path in authored_before} == authored_before
    assert check_artifacts(output, rendered) == ()
    assert snapshot() == after_write

    (output / "test-manifest.v1.json").write_text("{}\n")
    assert check_artifacts(output, rendered) == ("test-manifest.v1.json",)


def test_check_does_not_create_a_missing_output_directory(tmp_path: Path) -> None:
    output = tmp_path / "absent"
    rendered = render_target_artifacts(parse_target_artifacts_source(SOURCE_PATH.read_bytes()))

    assert check_artifacts(output, rendered) == (
        "execution-registry.v1.json",
        "test-manifest.v1.json",
        "dependency-graph.v1.json",
        CONTROL_FILENAME,
    )
    assert not output.exists()


def test_failed_replacement_removes_the_temporary_file(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    rendered = render_target_artifacts(parse_target_artifacts_source(SOURCE_PATH.read_bytes()))

    def reject_replace(_source: Path, _target: Path) -> Path:
        raise OSError("replacement failed")

    monkeypatch.setattr(Path, "replace", reject_replace)

    with pytest.raises(OSError, match="replacement failed"):
        write_artifacts(tmp_path, rendered)
    assert tuple(tmp_path.iterdir()) == ()


@pytest.mark.parametrize("fail_after_effect", [False, True], ids=("pre-effect", "post-effect"))
def test_replacement_failure_restores_the_complete_prior_artifact_set(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    fail_after_effect: bool,
) -> None:
    rendered = render_target_artifacts(parse_target_artifacts_source(SOURCE_PATH.read_bytes()))
    changed = replace(
        rendered,
        execution_registry=rendered.execution_registry + b" ",
        test_manifest=rendered.test_manifest + b" ",
        dependency_graph=rendered.dependency_graph + b" ",
        control_bundle=rendered.control_bundle + b" ",
    )
    original_replace = Path.replace
    for failed_replace in range(1, len(rendered.by_filename()) * 2 + 1):
        output = tmp_path / str(failed_replace)
        write_artifacts(output, rendered)
        before = {path.name: path.read_bytes() for path in output.iterdir()}
        calls = 0

        def fail_once(
            source: Path,
            target: Path,
            failed_replace: int = failed_replace,
        ) -> Path:
            nonlocal calls
            calls += 1
            if calls == failed_replace and not fail_after_effect:
                raise OSError("replacement failed")
            result = original_replace(source, target)
            if calls == failed_replace:
                raise OSError("replacement failed")
            return result

        with monkeypatch.context() as patch:
            patch.setattr(Path, "replace", fail_once)
            with pytest.raises(OSError, match="replacement failed"):
                write_artifacts(output, changed)

        assert {path.name: path.read_bytes() for path in output.iterdir()} == before
        assert not any(path.name.startswith(".") for path in output.iterdir())


def test_failed_rollback_preserves_the_prior_artifact_as_a_recovery_backup(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    rendered = render_target_artifacts(parse_target_artifacts_source(SOURCE_PATH.read_bytes()))
    write_artifacts(tmp_path, rendered)
    prior = rendered.execution_registry
    changed = replace(rendered, execution_registry=prior + b" ")
    original_replace = Path.replace
    calls = 0

    def fail_publication_and_recovery(source: Path, target: Path) -> Path:
        nonlocal calls
        calls += 1
        if calls == 3:
            raise OSError("rollback failed")
        result = original_replace(source, target)
        if calls == 2:
            raise OSError("publication failed")
        return result

    monkeypatch.setattr(Path, "replace", fail_publication_and_recovery)

    with pytest.raises(OSError, match="publication recovery failed"):
        write_artifacts(tmp_path, changed)

    backups = tuple(tmp_path.glob(".execution-registry.v1.json.backup.*"))
    assert len(backups) == 1
    assert backups[0].read_bytes() == prior


def test_cli_returns_distinct_success_drift_and_admission_codes(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    arguments = ["--source", str(SOURCE_PATH), "--output-directory", str(tmp_path)]

    assert main(["check", *arguments]) == 1
    assert "target_artifacts_drift" in capsys.readouterr().err
    assert main(["render", *arguments]) == 0
    assert "target_artifacts_rendered" in capsys.readouterr().out
    assert main(["check", *arguments]) == 0
    assert "target_artifacts_current" in capsys.readouterr().out

    invalid = tmp_path / "invalid.json"
    invalid.write_text("{}")
    assert main(["check", "--source", str(invalid), "--output-directory", str(tmp_path)]) == 2
    assert "target_artifacts_invalid" in capsys.readouterr().err


def test_plan_trust_root_cli_renders_and_checks_exact_ed25519_identity(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    public_key = tmp_path / "plan-signing.pub.pem"
    output = tmp_path / "plan-trust-root.v1.json"
    public_key.write_bytes(
        ed25519.Ed25519PrivateKey.generate()
        .public_key()
        .public_bytes(Encoding.PEM, PublicFormat.SubjectPublicKeyInfo)
    )
    arguments = [
        "--key-id",
        "release-key.2026-07",
        "--public-key",
        str(public_key),
        "--output",
        str(output),
    ]

    assert main(["check-trust-root", *arguments]) == 1
    assert "plan_trust_root_drift" in capsys.readouterr().err
    assert main(["render-trust-root", *arguments]) == 0
    assert "plan_trust_root_rendered" in capsys.readouterr().out
    expected = render_plan_trust_root(
        key_id="release-key.2026-07",
        public_key_pem=public_key.read_bytes(),
    )
    assert output.read_bytes() == expected
    assert check_plan_trust_root(output, expected)
    assert main(["check-trust-root", *arguments]) == 0
    assert "plan_trust_root_current" in capsys.readouterr().out


def test_plan_trust_root_rejects_non_ed25519_and_symlinked_artifacts(tmp_path: Path) -> None:
    rsa_key = rsa.generate_private_key(public_exponent=65537, key_size=2048).public_key()
    with pytest.raises(ValueError, match="Ed25519"):
        render_plan_trust_root(
            key_id="rsa-key",
            public_key_pem=rsa_key.public_bytes(Encoding.PEM, PublicFormat.SubjectPublicKeyInfo),
        )

    target = tmp_path / "target.json"
    link = tmp_path / "plan-trust-root.v1.json"
    target.write_bytes(b"{}\n")
    link.symlink_to(target)
    assert not check_plan_trust_root(link, b"{}\n")


def _enlarge_manifest(source: dict[str, object]) -> None:
    tests = _array(source["tests"])
    witness_id = _object(tests[0])["witnessId"]
    source["tests"] = [
        {
            "testId": f"{index:04d}-" + "x" * 240,
            "witnessId": witness_id,
            "expectedSeconds": 1,
        }
        for index in range(4_096)
    ]


def _object(value: object) -> dict[str, object]:
    assert isinstance(value, dict)
    return value


def _array(value: object) -> list[object]:
    assert isinstance(value, list)
    return value


def test_render_rejects_test_manifest_byte_overflow_before_write() -> None:
    source = json.loads(SOURCE_PATH.read_bytes())
    assert isinstance(source, dict)
    _enlarge_manifest(source)

    admitted = parse_target_artifacts_source(json.dumps(source).encode())

    with pytest.raises(TargetArtifactsRenderError, match="not runtime-admitted"):
        render_target_artifacts(admitted)
