"""Pure reconciliation domain contracts and classification."""

from ci_coordinator.reconciliation.check_summary import CheckSummary, summarize_check
from ci_coordinator.reconciliation.contract import (
    CandidateEvidenceContext,
    PlanningEvidenceContext,
    ReconciliationContract,
)
from ci_coordinator.reconciliation.convergence import (
    DEFAULT_RECONCILIATION_CONVERGENCE_POLICY,
    MAX_RECONCILIATION_ATTEMPTS,
    MAX_RECONCILIATION_BACKOFF_SECONDS,
    MAX_RECONCILIATION_DEADLINE_SECONDS,
    MAX_RECONCILIATION_LEASE_SECONDS,
    ConvergenceTerminalReason,
    ReconciliationAttemptClaim,
    ReconciliationClaimAcquired,
    ReconciliationClaimLost,
    ReconciliationConvergencePolicy,
    ReconciliationConvergenceState,
    ReconciliationTerminalRequired,
    acquire_reconciliation_claim,
    convergence_failure,
    defer_reconciliation_claim,
    initial_convergence_state,
    reconciliation_claim_is_active,
    release_terminal_claim,
)
from ci_coordinator.reconciliation.findings import (
    ReconciliationFinding,
    ReconciliationFindingKind,
    ReconciliationResult,
    ReconciliationState,
)
from ci_coordinator.reconciliation.observation import (
    OmittedSignal,
    SignalConclusion,
    SignalObservation,
    SignalStatus,
)
from ci_coordinator.reconciliation.poll_outcome import (
    ProviderSignalAmbiguity,
    ReconciliationPollOutcome,
    provider_signal_ambiguity_failure,
)
from ci_coordinator.reconciliation.ports import (
    ReconciliationPersistence,
    ReconciliationPoller,
    ReconciliationPollUnavailable,
    ReconciliationPublisher,
)
from ci_coordinator.reconciliation.reconciler import reconcile
from ci_coordinator.reconciliation.scheduler import (
    DrainResult,
    ReconciliationRound,
    ReconciliationScheduler,
    RoundCompletion,
    SchedulerShutdown,
    TickResult,
)
from ci_coordinator.reconciliation.snapshot import (
    ObservationAppend,
    ObservationAppended,
    ObservationConflict,
    ObservationDuplicate,
    ObservationRevisionConflict,
    ReconciliationSnapshot,
    ResultConflict,
    ResultDuplicate,
    ResultRecord,
    ResultRecorded,
    ResultRevisionConflict,
    SubjectRegistered,
    SubjectRegistration,
    SubjectRegistrationConflict,
    SubjectRegistrationDuplicate,
)
from ci_coordinator.reconciliation.state_machine import (
    ReconciliationInput,
    classify_observed_state,
)
from ci_coordinator.reconciliation.state_store import (
    append_observation,
    record_result,
    register_subject,
)
from ci_coordinator.reconciliation.subject import (
    RECONCILIATION_SUBJECT_SCHEMA_VERSION,
    ReconciliationSubject,
)

__all__ = [
    "DEFAULT_RECONCILIATION_CONVERGENCE_POLICY",
    "MAX_RECONCILIATION_ATTEMPTS",
    "MAX_RECONCILIATION_BACKOFF_SECONDS",
    "MAX_RECONCILIATION_DEADLINE_SECONDS",
    "MAX_RECONCILIATION_LEASE_SECONDS",
    "RECONCILIATION_SUBJECT_SCHEMA_VERSION",
    "CandidateEvidenceContext",
    "CheckSummary",
    "ConvergenceTerminalReason",
    "DrainResult",
    "ObservationAppend",
    "ObservationAppended",
    "ObservationConflict",
    "ObservationDuplicate",
    "ObservationRevisionConflict",
    "OmittedSignal",
    "PlanningEvidenceContext",
    "ProviderSignalAmbiguity",
    "ReconciliationAttemptClaim",
    "ReconciliationClaimAcquired",
    "ReconciliationClaimLost",
    "ReconciliationContract",
    "ReconciliationConvergencePolicy",
    "ReconciliationConvergenceState",
    "ReconciliationFinding",
    "ReconciliationFindingKind",
    "ReconciliationInput",
    "ReconciliationPersistence",
    "ReconciliationPollOutcome",
    "ReconciliationPollUnavailable",
    "ReconciliationPoller",
    "ReconciliationPublisher",
    "ReconciliationResult",
    "ReconciliationRound",
    "ReconciliationScheduler",
    "ReconciliationSnapshot",
    "ReconciliationState",
    "ReconciliationSubject",
    "ReconciliationTerminalRequired",
    "ResultConflict",
    "ResultDuplicate",
    "ResultRecord",
    "ResultRecorded",
    "ResultRevisionConflict",
    "RoundCompletion",
    "SchedulerShutdown",
    "SignalConclusion",
    "SignalObservation",
    "SignalStatus",
    "SubjectRegistered",
    "SubjectRegistration",
    "SubjectRegistrationConflict",
    "SubjectRegistrationDuplicate",
    "TickResult",
    "acquire_reconciliation_claim",
    "append_observation",
    "classify_observed_state",
    "convergence_failure",
    "defer_reconciliation_claim",
    "initial_convergence_state",
    "provider_signal_ambiguity_failure",
    "reconcile",
    "reconciliation_claim_is_active",
    "record_result",
    "register_subject",
    "release_terminal_claim",
    "summarize_check",
]
