"""Machine-owned fixed GitHub.com App transport constants."""

from __future__ import annotations

from typing import Final

GITHUB_API_BASE_URL: Final = "https://api.github.com"
GITHUB_API_VERSION: Final = "2026-03-10"
GITHUB_API_ACCEPT: Final = "application/vnd.github+json"
GITHUB_API_ACCEPT_ENCODING: Final = "identity"
GITHUB_API_USER_AGENT: Final = "ci-coordinator/0.1"
GITHUB_REQUEST_TIMEOUT_SECONDS: Final = 10
GITHUB_MAXIMUM_CONCURRENT_EXCHANGES: Final = 64
GITHUB_MAXIMUM_REQUEST_BODY_BYTES: Final = 1_048_576
GITHUB_MAXIMUM_RESPONSE_BODY_BYTES: Final = 8_388_608
GITHUB_MAXIMUM_INSTALLATION_ID: Final = 9_007_199_254_740_991
GITHUB_APP_JWT_BACKDATE_SECONDS: Final = 60
GITHUB_APP_JWT_LIFETIME_SECONDS: Final = 540
GITHUB_INSTALLATION_TOKEN_REFRESH_SKEW_SECONDS: Final = 300
GITHUB_MAXIMUM_CACHED_INSTALLATIONS: Final = 1_024
GITHUB_MAXIMUM_CONCURRENT_REFRESHES: Final = 64
GITHUB_MAXIMUM_RATE_LIMIT_INTEGER_DIGITS: Final = 16
