"""Process-settings admission boundary."""

from ci_coordinator.runtime_settings.admission import admit_runtime_settings
from ci_coordinator.runtime_settings.authority_contracts import (
    CallerInventory,
    CallerInventoryRejection,
    CallerRecord,
    EntrypointDiscoveryProfile,
    EntrypointDispositionInventory,
    EntrypointDispositionRecord,
    EntrypointDispositionRejection,
)
from ci_coordinator.runtime_settings.build_identity import (
    BUILD_IDENTITY_RESOURCE,
    BUILD_IDENTITY_SCHEMA,
    BuildIdentity,
    load_bundled_build_identity,
    parse_build_identity,
    render_build_identity,
)
from ci_coordinator.runtime_settings.caller_inventory import (
    INVENTORY_ID,
    INVENTORY_SCHEMA_VERSION,
    admit_caller_inventory,
    load_bundled_caller_inventory,
    parse_caller_inventory,
)
from ci_coordinator.runtime_settings.contracts import (
    ConnectedRuntimeSettings,
    ControlPlaneIdentitySettings,
    DisabledRuntimeSettings,
    EnforcingRuntimeSettings,
    NonEnforcingRuntimeSettings,
    RuntimeSettings,
    RuntimeSettingsProjection,
    RuntimeSettingsRejection,
    SecretValue,
    decode_control_plane_session_key,
    is_break_glass_bearer_token,
    is_metrics_bearer_token,
    normalize_bind_host,
    normalize_outbound_proxy_url,
)
from ci_coordinator.runtime_settings.entrypoint_disposition import (
    ENTRYPOINT_DISPOSITION_ID,
    ENTRYPOINT_DISPOSITION_SCHEMA_VERSION,
    admit_entrypoint_disposition,
    load_bundled_entrypoint_disposition,
    parse_entrypoint_disposition,
)
from ci_coordinator.runtime_settings.python_runtime import (
    PYTHON_RUNTIME_PROFILE,
    PYTHON_RUNTIME_PROFILE_ID,
    PYTHON_RUNTIME_PROFILE_SCHEMA,
    SUPPORTED_PYTHON_VERSIONS,
    PythonRuntimeProfile,
    UnsupportedPythonRuntime,
    admit_python_runtime,
    load_bundled_python_runtime_profile,
    parse_python_runtime_profile,
)
from ci_coordinator.runtime_settings.redaction import redacted_settings_projection

__all__ = [
    "BUILD_IDENTITY_RESOURCE",
    "BUILD_IDENTITY_SCHEMA",
    "ENTRYPOINT_DISPOSITION_ID",
    "ENTRYPOINT_DISPOSITION_SCHEMA_VERSION",
    "INVENTORY_ID",
    "INVENTORY_SCHEMA_VERSION",
    "PYTHON_RUNTIME_PROFILE",
    "PYTHON_RUNTIME_PROFILE_ID",
    "PYTHON_RUNTIME_PROFILE_SCHEMA",
    "SUPPORTED_PYTHON_VERSIONS",
    "BuildIdentity",
    "CallerInventory",
    "CallerInventoryRejection",
    "CallerRecord",
    "ConnectedRuntimeSettings",
    "ControlPlaneIdentitySettings",
    "DisabledRuntimeSettings",
    "EnforcingRuntimeSettings",
    "EntrypointDiscoveryProfile",
    "EntrypointDispositionInventory",
    "EntrypointDispositionRecord",
    "EntrypointDispositionRejection",
    "NonEnforcingRuntimeSettings",
    "PythonRuntimeProfile",
    "RuntimeSettings",
    "RuntimeSettingsProjection",
    "RuntimeSettingsRejection",
    "SecretValue",
    "UnsupportedPythonRuntime",
    "admit_caller_inventory",
    "admit_entrypoint_disposition",
    "admit_python_runtime",
    "admit_runtime_settings",
    "decode_control_plane_session_key",
    "is_break_glass_bearer_token",
    "is_metrics_bearer_token",
    "load_bundled_build_identity",
    "load_bundled_caller_inventory",
    "load_bundled_entrypoint_disposition",
    "load_bundled_python_runtime_profile",
    "normalize_bind_host",
    "normalize_outbound_proxy_url",
    "parse_build_identity",
    "parse_caller_inventory",
    "parse_entrypoint_disposition",
    "parse_python_runtime_profile",
    "redacted_settings_projection",
    "render_build_identity",
]
