from __future__ import annotations

import json
import shutil
import sys
import textwrap
from pathlib import Path

import pytest
from scripts.target_control_bundle import (
    BUNDLE_PATH,
    ESBUILD_VERSION,
    SOURCE_ROOT,
    TargetControlBundleError,
    check_bundle,
    render_bundle,
    write_bundle,
)


def test_rendered_bundle_is_deterministic_and_sensitive_to_every_source_byte(
    tmp_path: Path,
) -> None:
    source_root = _copy_sources(tmp_path)
    esbuild = _fake_esbuild(tmp_path)

    first = render_bundle(source_root=source_root, esbuild=str(esbuild))
    second = render_bundle(source_root=source_root, esbuild=str(esbuild))

    assert first == second
    assert first.startswith(
        b"// Generated by scripts.target_control_bundle; do not edit; source-sha256="
    )
    assert first.endswith(b'"use strict";\n')

    source = source_root / "validation_core.cjs"
    source.write_bytes(source.read_bytes() + b"// changed\n")
    changed = render_bundle(source_root=source_root, esbuild=str(esbuild))

    assert changed != first
    assert changed.splitlines()[1:] == first.splitlines()[1:]


def test_write_and_check_use_exact_regular_bytes(tmp_path: Path) -> None:
    source_root = _copy_sources(tmp_path)
    esbuild = _fake_esbuild(tmp_path)
    bundle = tmp_path / "ci-coordinator.cjs"

    assert not check_bundle(
        source_root=source_root,
        bundle_path=bundle,
        esbuild=str(esbuild),
    )
    write_bundle(source_root=source_root, bundle_path=bundle, esbuild=str(esbuild))
    assert check_bundle(
        source_root=source_root,
        bundle_path=bundle,
        esbuild=str(esbuild),
    )

    _, body = bundle.read_bytes().split(b"\n", maxsplit=1)
    bundle.write_bytes(b"// malformed generated header\n" + body)
    assert not check_bundle(
        source_root=source_root,
        bundle_path=bundle,
        esbuild=str(esbuild),
    )

    write_bundle(source_root=source_root, bundle_path=bundle, esbuild=str(esbuild))
    bundle.write_bytes(bundle.read_bytes() + b" ")
    assert not check_bundle(
        source_root=source_root,
        bundle_path=bundle,
        esbuild=str(esbuild),
    )
    bundle.unlink()
    bundle.symlink_to(BUNDLE_PATH)
    assert not check_bundle(
        source_root=source_root,
        bundle_path=bundle,
        esbuild=str(esbuild),
    )


@pytest.mark.parametrize("mutation", ["missing", "extra", "symlink"])
def test_source_inventory_must_be_exact_regular_files(tmp_path: Path, mutation: str) -> None:
    source_root = _copy_sources(tmp_path)
    if mutation == "missing":
        (source_root / "validation_core.cjs").unlink()
    elif mutation == "extra":
        (source_root / "extra.cjs").write_bytes(b'"use strict";\n')
    elif mutation == "symlink":
        source = source_root / "validation_core.cjs"
        source.unlink()
        source.symlink_to(SOURCE_ROOT / "validation_core.cjs")
    else:  # pragma: no cover - closed parameter set
        raise AssertionError("unknown test mutation")

    with pytest.raises(TargetControlBundleError):
        render_bundle(source_root=source_root, esbuild=str(_fake_esbuild(tmp_path)))


def test_esbuild_version_and_quiet_output_are_exact(tmp_path: Path) -> None:
    source_root = _copy_sources(tmp_path)

    with pytest.raises(TargetControlBundleError, match="version"):
        render_bundle(
            source_root=source_root,
            esbuild=str(_fake_esbuild(tmp_path, version="0.0.0")),
        )

    with pytest.raises(TargetControlBundleError, match="quiet"):
        render_bundle(
            source_root=source_root,
            esbuild=str(_fake_esbuild(tmp_path, build_noise=True)),
        )


@pytest.mark.parametrize(
    ("build_status", "bundle_size", "message"),
    (
        (7, 14, "failed"),
        (0, 1_048_577, "bounded regular file"),
    ),
)
def test_esbuild_failure_and_output_overflow_are_rejected(
    tmp_path: Path,
    build_status: int,
    bundle_size: int,
    message: str,
) -> None:
    with pytest.raises(TargetControlBundleError, match=message):
        render_bundle(
            source_root=_copy_sources(tmp_path),
            esbuild=str(
                _fake_esbuild(
                    tmp_path,
                    build_status=build_status,
                    bundle_size=bundle_size,
                )
            ),
        )


@pytest.mark.parametrize(
    ("metafile_mutation", "message"),
    (
        ("cycle", "cycle"),
        ("external", "external import"),
        ("missing-input", "input inventory"),
    ),
)
def test_esbuild_metafile_must_prove_closed_acyclic_source_graph(
    tmp_path: Path,
    metafile_mutation: str,
    message: str,
) -> None:
    source_root = _copy_sources(tmp_path)
    if metafile_mutation == "cycle":
        source = source_root / "validation_core.cjs"
        source.write_bytes(source.read_bytes() + b'require("./main.cjs");\n')

    with pytest.raises(TargetControlBundleError, match=message):
        render_bundle(
            source_root=source_root,
            esbuild=str(_fake_esbuild(tmp_path, metafile_mutation=metafile_mutation)),
        )


@pytest.mark.parametrize(
    "metafile_mutation",
    ("missing-dependency", "output-missing-external"),
)
def test_esbuild_metafile_must_equal_independent_source_graph(
    tmp_path: Path,
    metafile_mutation: str,
) -> None:
    with pytest.raises(TargetControlBundleError, match="dependencies differ"):
        render_bundle(
            source_root=_copy_sources(tmp_path),
            esbuild=str(_fake_esbuild(tmp_path, metafile_mutation=metafile_mutation)),
        )


def _copy_sources(tmp_path: Path) -> Path:
    destination = tmp_path / "source"
    shutil.copytree(SOURCE_ROOT, destination)
    return destination


def _fake_esbuild(
    tmp_path: Path,
    *,
    build_status: int = 0,
    bundle_size: int = 14,
    version: str = ESBUILD_VERSION,
    build_noise: bool = False,
    metafile_mutation: str = "none",
) -> Path:
    executable = tmp_path / (
        f"esbuild-{version}-{int(build_noise)}-{build_status}-{bundle_size}-{metafile_mutation}"
    )
    settings = json.dumps(
        {
            "buildNoise": build_noise,
            "buildStatus": build_status,
            "bundleSize": bundle_size,
            "metafileMutation": metafile_mutation,
            "version": version,
        },
        separators=(",", ":"),
        sort_keys=True,
    )
    executable.write_text(
        f"#!{sys.executable}\n"
        + textwrap.dedent(
            f"""
            import json
            import sys
            from pathlib import Path

            SETTINGS = json.loads({settings!r})
            IMPORTS = {{
                "consume_plan.cjs": (("node:fs", True), ("node:zlib", True)),
                "main.cjs": (
                    ("consume_plan.cjs", False),
                    ("validate_gate.cjs", False),
                    ("validate_plan.cjs", False),
                ),
                "validate_gate.cjs": (
                    ("validation_core.cjs", False),
                    ("validation_execution.cjs", False),
                ),
                "validate_plan.cjs": (
                    ("validation_core.cjs", False),
                    ("validation_envelope.cjs", False),
                    ("validation_execution.cjs", False),
                ),
                "validation_core.cjs": (
                    ("node:crypto", True),
                    ("node:fs", True),
                    ("node:util", True),
                ),
                "validation_envelope.cjs": (
                    ("node:crypto", True),
                    ("validation_core.cjs", False),
                ),
                "validation_execution.cjs": (
                    ("validation_core.cjs", False),
                    ("validation_envelope.cjs", False),
                ),
            }}
            EXPECTED = [
                "main.cjs",
                "--bundle",
                "--platform=node",
                "--format=cjs",
                "--target=node24",
                "--charset=utf8",
                "--legal-comments=none",
                "--log-level=warning",
                "--metafile=metafile.json",
                "--outfile=bundle.cjs",
            ]

            if sys.argv[1:] == ["--version"]:
                print(SETTINGS["version"])
                raise SystemExit(0)
            if sys.argv[1:] != EXPECTED:
                raise SystemExit(9)
            if SETTINGS["buildStatus"] != 0:
                raise SystemExit(SETTINGS["buildStatus"])

            body = b'"use strict";\\n'
            if SETTINGS["bundleSize"] != len(body):
                body = b'x' * (SETTINGS["bundleSize"] - 1) + b'\\n'
            Path("bundle.cjs").write_bytes(body)
            inputs = {{}}
            for source_path, imports in IMPORTS.items():
                rows = []
                for imported_path, external in imports:
                    row = {{"kind": "require-call", "path": imported_path}}
                    if external:
                        row["external"] = True
                    else:
                        row["original"] = f"./{{imported_path}}"
                    rows.append(row)
                inputs[source_path] = {{
                    "bytes": Path(source_path).stat().st_size,
                    "format": "cjs",
                    "imports": rows,
                }}
            mutation = SETTINGS["metafileMutation"]
            if mutation == "cycle":
                inputs["validation_core.cjs"]["imports"].append({{
                    "kind": "require-call",
                    "original": "./main.cjs",
                    "path": "main.cjs",
                }})
            elif mutation == "external":
                inputs["main.cjs"]["imports"].append({{
                    "external": True,
                    "kind": "require-call",
                    "path": "foreign-package",
                }})
            elif mutation == "missing-input":
                del inputs["validation_core.cjs"]
            elif mutation == "missing-dependency":
                del inputs["main.cjs"]["imports"][0]
            elif mutation != "none":
                if mutation != "output-missing-external":
                    raise SystemExit(10)
            output_imports = [
                {{"external": True, "kind": "require-call", "path": imported_path}}
                for imports in IMPORTS.values()
                for imported_path, external in imports
                if external
            ]
            if mutation == "output-missing-external":
                del output_imports[0]
            metafile = {{
                "inputs": inputs,
                "outputs": {{
                    "bundle.cjs": {{
                        "bytes": len(body),
                        "entryPoint": "main.cjs",
                        "exports": [],
                        "imports": output_imports,
                        "inputs": {{
                            source_path: {{"bytesInOutput": 1}}
                            for source_path in inputs
                        }},
                    }}
                }},
            }}
            Path("metafile.json").write_text(
                json.dumps(metafile, separators=(",", ":"), sort_keys=True),
                encoding="utf-8",
            )
            if SETTINGS["buildNoise"]:
                print("unexpected output", file=sys.stderr)
            """
        ).lstrip(),
        encoding="utf-8",
    )
    executable.chmod(0o755)
    return executable
