from __future__ import annotations

import argparse
import hashlib
import json
import os
import stat
import sys
import tempfile
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Final

from scripts.bounded_process import spawn
from scripts.target_control_paths import (
    _SOURCE_FILENAMES as _SOURCE_FILENAMES,
)
from scripts.target_control_paths import (
    BUNDLE_PATH as BUNDLE_PATH,
)
from scripts.target_control_paths import (
    REPO_ROOT as REPO_ROOT,
)
from scripts.target_control_paths import (
    SOURCE_ROOT as SOURCE_ROOT,
)
from scripts.target_control_source_admission import (
    SourceDependencyGraph,
    TargetControlSourceAdmissionError,
    admit_source_dependency_graph,
)

ESBUILD_VERSION: Final = "0.28.2"
SOURCE_SCHEMA: Final = "ci-coordinator-target-control-source/v1"
_ENTRYPOINT: Final = "main.cjs"
_BUNDLE_FILENAME: Final = "bundle.cjs"
_METAFILE_FILENAME: Final = "metafile.json"
_ALLOWED_EXTERNAL_IMPORTS: Final = frozenset({"node:crypto", "node:fs", "node:util", "node:zlib"})
_MAX_SOURCE_BYTES: Final = 1_048_576
_MAX_TOTAL_SOURCE_BYTES: Final = 2_097_152
_MAX_BUNDLE_BYTES: Final = 1_048_576
_MAX_METAFILE_BYTES: Final = 1_048_576
_MAX_PROCESS_OUTPUT_BYTES: Final = 65_536
_BUILD_TIMEOUT_SECONDS: Final = 60
_BUILD_ARGUMENTS: Final = (
    "--bundle",
    "--platform=node",
    "--format=cjs",
    "--target=node24",
    "--charset=utf8",
    "--legal-comments=none",
    "--log-level=warning",
    f"--metafile={_METAFILE_FILENAME}",
    f"--outfile={_BUNDLE_FILENAME}",
)


class TargetControlBundleError(RuntimeError):
    """The target-control source or generated projection is not admitted."""


def render_bundle(
    *,
    source_root: Path = SOURCE_ROOT,
    esbuild: str | None = None,
) -> bytes:
    sources = _read_source_snapshot(source_root)
    try:
        source_graph = admit_source_dependency_graph(
            sources,
            allowed_external_imports=_ALLOWED_EXTERNAL_IMPORTS,
        )
    except TargetControlSourceAdmissionError as error:
        raise TargetControlBundleError(str(error)) from error
    source_identity = _source_identity(sources)
    executable = esbuild or str(REPO_ROOT / "node_modules" / ".bin" / "esbuild")
    if not Path(executable).is_file():
        raise TargetControlBundleError("repository-local esbuild executable is unavailable")
    with tempfile.TemporaryDirectory(prefix="ci-target-control-bundle-") as temporary:
        build_root = Path(temporary)
        for filename, content in sources.items():
            (build_root / filename).write_bytes(content)
        _require_esbuild_version(executable, build_root)
        completed = spawn(
            executable,
            (_ENTRYPOINT, *_BUILD_ARGUMENTS),
            cwd=build_root,
            env=_build_environment(executable),
            max_buffer=_MAX_PROCESS_OUTPUT_BYTES,
            timeout_seconds=_BUILD_TIMEOUT_SECONDS,
        )
        if (
            completed.status != 0
            or completed.error is not None
            or completed.stdout
            or completed.stderr
        ):
            raise TargetControlBundleError("esbuild failed to produce a quiet exact bundle")
        body = _read_regular_file(build_root / _BUNDLE_FILENAME, _MAX_BUNDLE_BYTES)
        _admit_metafile(
            build_root / _METAFILE_FILENAME,
            sources=sources,
            source_graph=source_graph,
            body=body,
        )
    if not body or not body.endswith(b"\n") or b"\x00" in body:
        raise TargetControlBundleError("esbuild output is not an admitted text bundle")
    try:
        body.decode("utf-8", errors="strict")
    except UnicodeDecodeError as error:
        raise TargetControlBundleError("esbuild output is not UTF-8") from error
    header = (
        "// Generated by scripts.target_control_bundle; do not edit; "
        f"source-sha256={source_identity}; esbuild={ESBUILD_VERSION}.\n"
    ).encode("ascii")
    rendered = header + body
    if len(rendered) > _MAX_BUNDLE_BYTES:
        raise TargetControlBundleError("generated target-control bundle exceeded its byte bound")
    return rendered


def check_bundle(
    *,
    source_root: Path = SOURCE_ROOT,
    bundle_path: Path = BUNDLE_PATH,
    esbuild: str | None = None,
) -> bool:
    expected = render_bundle(source_root=source_root, esbuild=esbuild)
    try:
        actual = _read_regular_file(bundle_path, _MAX_BUNDLE_BYTES)
    except TargetControlBundleError:
        return False
    return actual == expected


def write_bundle(
    *,
    source_root: Path = SOURCE_ROOT,
    bundle_path: Path = BUNDLE_PATH,
    esbuild: str | None = None,
) -> None:
    content = render_bundle(source_root=source_root, esbuild=esbuild)
    bundle_path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=bundle_path.parent,
        prefix=f".{bundle_path.name}.staged.",
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as output:
            output.write(content)
            output.flush()
            os.fsync(output.fileno())
        os.replace(temporary_path, bundle_path)
        directory = os.open(bundle_path.parent, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
    finally:
        temporary_path.unlink(missing_ok=True)


def _read_source_snapshot(source_root: Path) -> dict[str, bytes]:
    if not source_root.is_dir() or source_root.is_symlink():
        raise TargetControlBundleError("target-control source root is unavailable")
    try:
        with os.scandir(source_root) as entries:
            observed = tuple(sorted(entry.name for entry in entries))
    except OSError as error:
        raise TargetControlBundleError("target-control source inventory is unavailable") from error
    if observed != _SOURCE_FILENAMES:
        raise TargetControlBundleError("target-control source inventory is not exact")
    sources: dict[str, bytes] = {}
    total = 0
    for filename in _SOURCE_FILENAMES:
        content = _read_regular_file(source_root / filename, _MAX_SOURCE_BYTES)
        if not content or not content.endswith(b"\n") or b"\x00" in content:
            raise TargetControlBundleError("target-control source is not admitted text")
        try:
            content.decode("utf-8", errors="strict")
        except UnicodeDecodeError as error:
            raise TargetControlBundleError("target-control source is not UTF-8") from error
        total += len(content)
        if total > _MAX_TOTAL_SOURCE_BYTES:
            raise TargetControlBundleError("target-control source set exceeded its byte bound")
        sources[filename] = content
    return sources


def _read_regular_file(path: Path, maximum_bytes: int) -> bytes:
    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as error:
        raise TargetControlBundleError("target-control file is unavailable") from error
    try:
        before = os.fstat(descriptor)
        if not stat.S_ISREG(before.st_mode) or not 0 <= before.st_size <= maximum_bytes:
            raise TargetControlBundleError("target-control file is not a bounded regular file")
        content = bytearray()
        while len(content) <= maximum_bytes:
            chunk = os.read(descriptor, min(65_536, maximum_bytes + 1 - len(content)))
            if not chunk:
                break
            content.extend(chunk)
        after = os.fstat(descriptor)
    finally:
        os.close(descriptor)
    if len(content) > maximum_bytes:
        raise TargetControlBundleError("target-control file exceeded its byte bound")
    if (before.st_dev, before.st_ino, before.st_size, before.st_mtime_ns) != (
        after.st_dev,
        after.st_ino,
        after.st_size,
        after.st_mtime_ns,
    ) or len(content) != before.st_size:
        raise TargetControlBundleError("target-control file changed while it was read")
    return bytes(content)


def _source_identity(sources: Mapping[str, bytes]) -> str:
    manifest = {
        "buildArguments": list(_BUILD_ARGUMENTS),
        "entrypoint": _ENTRYPOINT,
        "esbuildVersion": ESBUILD_VERSION,
        "schemaVersion": SOURCE_SCHEMA,
        "sources": [
            {"path": path, "sha256": hashlib.sha256(content).hexdigest()}
            for path, content in sources.items()
        ],
    }
    encoded = json.dumps(
        manifest,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("ascii")
    return hashlib.sha256(encoded).hexdigest()


def _admit_metafile(
    path: Path,
    *,
    sources: Mapping[str, bytes],
    source_graph: SourceDependencyGraph,
    body: bytes,
) -> None:
    try:
        decoded = json.loads(_read_regular_file(path, _MAX_METAFILE_BYTES))
    except (json.JSONDecodeError, UnicodeDecodeError) as error:
        raise TargetControlBundleError("esbuild metafile is not valid JSON") from error
    if not isinstance(decoded, dict) or set(decoded) != {"inputs", "outputs"}:
        raise TargetControlBundleError("esbuild metafile root is not exact")
    inputs = decoded.get("inputs")
    outputs = decoded.get("outputs")
    if not isinstance(inputs, dict) or set(inputs) != set(sources):
        raise TargetControlBundleError("esbuild metafile input inventory is not exact")
    graph: dict[str, set[str]] = {}
    for source_path, source_bytes in sources.items():
        value = inputs.get(source_path)
        if not isinstance(value, dict) or set(value) != {"bytes", "format", "imports"}:
            raise TargetControlBundleError("esbuild metafile input is not exact")
        if value.get("bytes") != len(source_bytes) or value.get("format") != "cjs":
            raise TargetControlBundleError("esbuild metafile input identity is invalid")
        imports = value.get("imports")
        if not isinstance(imports, list):
            raise TargetControlBundleError("esbuild metafile imports are invalid")
        internal: list[str] = []
        external: list[str] = []
        for imported in imports:
            if not isinstance(imported, dict) or imported.get("kind") != "require-call":
                raise TargetControlBundleError("esbuild metafile import kind is invalid")
            imported_path = imported.get("path")
            if imported.get("external") is True:
                if (
                    set(imported) != {"external", "kind", "path"}
                    or imported_path not in _ALLOWED_EXTERNAL_IMPORTS
                ):
                    raise TargetControlBundleError("esbuild metafile external import is invalid")
                external.append(str(imported_path))
                continue
            if (
                set(imported) != {"kind", "original", "path"}
                or imported_path not in sources
                or imported.get("original") != f"./{imported_path}"
            ):
                raise TargetControlBundleError("esbuild metafile internal import is invalid")
            internal.append(str(imported_path))
        expected = source_graph.module(source_path)
        if (
            tuple(sorted(internal)) != expected.internal
            or tuple(sorted(external)) != expected.external
        ):
            raise TargetControlBundleError("source AST and esbuild metafile dependencies differ")
        graph[source_path] = set(internal)
    _require_acyclic_graph(graph)

    if not isinstance(outputs, dict) or set(outputs) != {_BUNDLE_FILENAME}:
        raise TargetControlBundleError("esbuild metafile output inventory is not exact")
    output = outputs.get(_BUNDLE_FILENAME)
    if not isinstance(output, dict) or set(output) != {
        "bytes",
        "entryPoint",
        "exports",
        "imports",
        "inputs",
    }:
        raise TargetControlBundleError("esbuild metafile output is not exact")
    if (
        output.get("bytes") != len(body)
        or output.get("entryPoint") != _ENTRYPOINT
        or output.get("exports") != []
    ):
        raise TargetControlBundleError("esbuild metafile output identity is invalid")
    output_inputs = output.get("inputs")
    if not isinstance(output_inputs, dict) or set(output_inputs) != set(sources):
        raise TargetControlBundleError("esbuild metafile reachable input set is not exact")
    for value in output_inputs.values():
        if (
            not isinstance(value, dict)
            or set(value) != {"bytesInOutput"}
            or type(value.get("bytesInOutput")) is not int
            or not 0 < value["bytesInOutput"] <= len(body)
        ):
            raise TargetControlBundleError("esbuild metafile output contribution is invalid")
    output_imports = output.get("imports")
    if not isinstance(output_imports, list):
        raise TargetControlBundleError("esbuild metafile output import is invalid")
    observed_output_imports: list[str] = []
    for imported in output_imports:
        if (
            not isinstance(imported, dict)
            or set(imported) != {"external", "kind", "path"}
            or imported.get("external") is not True
            or imported.get("kind") != "require-call"
            or imported.get("path") not in _ALLOWED_EXTERNAL_IMPORTS
        ):
            raise TargetControlBundleError("esbuild metafile output import is invalid")
        observed_output_imports.append(str(imported["path"]))
    if tuple(sorted(observed_output_imports)) != source_graph.external_occurrences:
        raise TargetControlBundleError("source AST and esbuild output dependencies differ")


def _require_acyclic_graph(graph: Mapping[str, set[str]]) -> None:
    visiting: set[str] = set()
    visited: set[str] = set()

    def visit(node: str) -> None:
        if node in visiting:
            raise TargetControlBundleError("target-control source dependency cycle detected")
        if node in visited:
            return
        visiting.add(node)
        for dependency in sorted(graph[node]):
            visit(dependency)
        visiting.remove(node)
        visited.add(node)

    for node in sorted(graph):
        visit(node)


def _require_esbuild_version(esbuild: str, cwd: Path) -> None:
    completed = spawn(
        esbuild,
        ("--version",),
        cwd=cwd,
        env=_build_environment(esbuild),
        max_buffer=128,
        timeout_seconds=_BUILD_TIMEOUT_SECONDS,
    )
    if (
        completed.status != 0
        or completed.error is not None
        or completed.stdout != f"{ESBUILD_VERSION}\n"
        or completed.stderr
    ):
        raise TargetControlBundleError("exact esbuild version is unavailable")


def _build_environment(executable: str) -> dict[str, str]:
    path = os.environ.get("PATH", "")
    executable_parent = str(Path(executable).resolve().parent)
    return {
        "FORCE_COLOR": "0",
        "LANG": "C",
        "LC_ALL": "C",
        "NO_COLOR": "1",
        "PATH": f"{executable_parent}{os.pathsep}{path}",
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m scripts.target_control_bundle")
    parser.add_argument("command", choices=("check", "write"))
    arguments = parser.parse_args(argv)
    try:
        if arguments.command == "write":
            write_bundle()
            status = "written"
        elif check_bundle():
            status = "current"
        else:
            raise TargetControlBundleError("generated target-control bundle is stale")
    except (OSError, TargetControlBundleError, ValueError) as error:
        print(
            json.dumps(
                {"code": "target_control_bundle_invalid", "detail": str(error)},
                separators=(",", ":"),
                sort_keys=True,
            ),
            file=sys.stderr,
        )
        return 1
    print(
        json.dumps(
            {"code": f"target_control_bundle_{status}", "file": str(BUNDLE_PATH)},
            separators=(",", ":"),
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
